# Author: Lindsey Tam
# Date Created: June 10 2020
# Description: This file sets the default value of the button setting
# Acknowledgements: This code is inspired by https://github.com/techAPJ/discourse-custom-topic-button/blob/master/plugin.rb

plugins:
  custom_topic_button_enabled:
    default: true
    client: true

